import React, { useEffect, useState } from 'react';
import financeApi from '../services/financeApi';

const today = new Date().toISOString().slice(0, 10);
const money = v => `₹${Number(v || 0).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;

export default function DebtManagement() {
  const [debts,setDebts]=useState([]),[accounts,setAccounts]=useState([]),[form,setForm]=useState({name:'',principalAmount:'',outstandingAmount:'',interestRate:'',minimumPayment:'',dueDay:''});
  const [payment,setPayment]=useState({amount:'',accountId:'',paymentDate:today}),[selected,setSelected]=useState(null),[editing,setEditing]=useState(null),[error,setError]=useState('');
  const load=async()=>{try{const [d,a]=await Promise.all([financeApi.debts.list(),financeApi.accounts.list()]);setDebts(d.data||[]);const active=(a.data||[]).filter(x=>x.isActive);setAccounts(active);setPayment(p=>({...p,accountId:p.accountId||active[0]?.id||''}));}catch(e){setError(e.response?.data?.message||'Unable to load debts.');}};
  useEffect(()=>{load();},[]);
  const save=async e=>{e.preventDefault();try{editing?await financeApi.debts.update(editing,form):await financeApi.debts.create(form);setEditing(null);setForm({name:'',principalAmount:'',outstandingAmount:'',interestRate:'',minimumPayment:'',dueDay:''});await load();}catch(x){setError(x.response?.data?.message||'Unable to save debt.');}};
  const addPayment=async(e,id)=>{e.preventDefault();try{await financeApi.debts.addPayment(id,payment);setPayment(p=>({...p,amount:'',paymentDate:today}));await load();}catch(x){setError(x.response?.data?.message||'Unable to record payment.');}};
  const archive=async id=>{if(window.confirm('Archive this debt?')){try{await financeApi.debts.remove(id);await load();}catch(x){setError(x.response?.data?.message||'Unable to archive debt.');}}};
  const totals=debts.reduce((x,d)=>({principal:x.principal+Number(d.principalAmount),outstanding:x.outstanding+Number(d.outstandingAmount)}),{principal:0,outstanding:0});
  return <div style={s.container}><h1 style={s.header}>Debt Management</h1>{error&&<div style={s.error}>{error}</div>}
    <div style={s.summary}><Card t="Total Debts" v={debts.length}/><Card t="Total Borrowed" v={money(totals.principal)}/><Card t="Total Paid" v={money(totals.principal-totals.outstanding)}/><Card t="Outstanding" v={money(totals.outstanding)}/></div>
    <div style={s.columns}><div style={s.panel}><h2>{editing?'Edit Debt':'Add Debt'}</h2><form style={s.form} onSubmit={save}>
      <label>Name</label><input style={s.input} value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><label>Principal Amount</label><input style={s.input} type="number" min="0.01" step="0.01" value={form.principalAmount} onChange={e=>setForm({...form,principalAmount:e.target.value})} required/>{!editing&&<><label>Current Outstanding</label><input style={s.input} type="number" min="0" step="0.01" value={form.outstandingAmount} onChange={e=>setForm({...form,outstandingAmount:e.target.value})}/></>}<label>Interest Rate (%)</label><input style={s.input} type="number" min="0" max="100" step="0.0001" value={form.interestRate} onChange={e=>setForm({...form,interestRate:e.target.value})}/><label>Minimum Payment</label><input style={s.input} type="number" min="0.01" step="0.01" value={form.minimumPayment} onChange={e=>setForm({...form,minimumPayment:e.target.value})}/><label>Due Day</label><input style={s.input} type="number" min="1" max="31" value={form.dueDay} onChange={e=>setForm({...form,dueDay:e.target.value})}/><button style={s.button}>{editing?'Update Debt':'Add Debt'}</button>{editing&&<button type="button" style={s.cancel} onClick={()=>{setEditing(null);setForm({name:'',principalAmount:'',outstandingAmount:'',interestRate:'',minimumPayment:'',dueDay:''})}}>Cancel</button>}</form></div>
    <div style={s.panel}><h2>Your Debts</h2>{debts.length===0?<p>No debts recorded yet.</p>:debts.map(d=><div style={s.debt} key={d.id}><div style={s.row}><h3>{d.name}</h3><span>{d.status.replace('_',' ')}</span></div><div style={s.row}><strong>{money(d.outstandingAmount)}</strong><span>of {money(d.principalAmount)} outstanding</span></div><div style={s.track}><div style={{...s.fill,width:`${d.progressPercent}%`}}/></div><div style={s.meta}>{d.progressPercent}% paid • {d.interestRate}% interest{d.dueDay?` • Due ${d.dueDay}`:''}</div><button style={s.link} onClick={()=>setSelected(selected===d.id?null:d.id)}>{selected===d.id?'Hide Payments':'Make / View Payments'}</button><button style={s.small} onClick={()=>{setEditing(d.id);setForm({name:d.name,principalAmount:d.principalAmount,outstandingAmount:'',interestRate:d.interestRate,minimumPayment:d.minimumPayment||'',dueDay:d.dueDay||''})}}>Edit</button>{d.status!=='ARCHIVED'&&<button style={s.danger} onClick={()=>archive(d.id)}>Archive</button>}{selected===d.id&&<div style={s.payment}>{d.status!=='PAID_OFF'&&<form style={s.form} onSubmit={e=>addPayment(e,d.id)}><label>Payment Amount</label><input style={s.input} type="number" min="0.01" max={d.outstandingAmount} step="0.01" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} required/><label>Paid From</label><select style={s.input} value={payment.accountId} onChange={e=>setPayment({...payment,accountId:e.target.value})} required><option value="">Select account</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select><label>Payment Date</label><input style={s.input} type="date" max={today} value={payment.paymentDate} onChange={e=>setPayment({...payment,paymentDate:e.target.value})} required/><button style={s.button}>Record Payment</button></form>}<h4>Payment History</h4>{d.payments.map(p=><div style={s.row} key={p.id}><span>{money(p.amount)} • {p.paymentDate}</span><button style={s.danger} onClick={async()=>{if(window.confirm('Reverse payment?')){await financeApi.debts.removePayment(d.id,p.id);await load();}}}>Reverse</button></div>)}</div>}</div>)}</div></div></div>;
}
function Card({t,v}){return <div style={s.card}><span>{t}</span><strong>{v}</strong></div>}
const s={container:{fontFamily:'"Rubik", sans-serif',maxWidth:'1200px',margin:'0 auto',padding:20},header:{textAlign:'center',color:'#4CAF50'},error:{padding:12,background:'#FDECEC',color:'#C0392B',borderRadius:6,marginBottom:20},summary:{display:'flex',gap:15,flexWrap:'wrap',marginBottom:20},card:{flex:1,minWidth:170,padding:18,background:'#f8f9fa',borderRadius:8,display:'flex',justifyContent:'space-between'},columns:{display:'flex',gap:20},panel:{flex:1,padding:20,background:'#f8f9fa',borderRadius:8},form:{display:'flex',flexDirection:'column',gap:6},input:{padding:10,border:'1px solid #ced4da',borderRadius:4,marginBottom:8,fontFamily:'inherit'},button:{padding:'10px 16px',background:'#007bff',color:'#fff',border:0,borderRadius:4,cursor:'pointer',marginRight:8},cancel:{padding:'10px 16px',background:'#dc3545',color:'#fff',border:0,borderRadius:4},debt:{padding:18,marginBottom:14,border:'1px solid #dee2e6',borderRadius:8},row:{display:'flex',justifyContent:'space-between',alignItems:'center',gap:10},track:{height:14,background:'#e9ecef',borderRadius:10,overflow:'hidden'},fill:{height:'100%',background:'#4CAF50'},meta:{fontSize:13,color:'#666',margin:'7px 0'},link:{border:0,background:'transparent',color:'#007bff',cursor:'pointer',fontWeight:'bold',marginRight:10},small:{background:'blue',color:'#fff',border:0,padding:'5px 10px',borderRadius:5,marginRight:6},danger:{background:'red',color:'#fff',border:0,padding:'5px 10px',borderRadius:5},payment:{marginTop:15,paddingTop:15,borderTop:'1px solid #ddd'}};
