const express = require('express');
const authenticateToken = require('../middlewares/authMiddleware');
const savingsGoalService = require('../services/savingsGoalService');
const AppError = require('../utils/AppError');
const router = express.Router();
router.use(authenticateToken);
router.get('/', async (req, res, next) => { try { return res.json(await savingsGoalService.list(req.user.id)); } catch (error) { return next(error); } });
router.post('/', async (req, res, next) => { try { return res.status(201).json(await savingsGoalService.create(req.user.id, req.body || {})); } catch (error) { return next(error); } });
router.patch('/:id', async (req, res, next) => { try { const goal = await savingsGoalService.update(req.user.id, req.params.id, req.body || {}); if (!goal) return next(new AppError('Savings goal not found.', 404)); return res.json(goal); } catch (error) { return next(error); } });
router.delete('/:id', async (req, res, next) => { try { const deleted = await savingsGoalService.remove(req.user.id, req.params.id); if (!deleted) return next(new AppError('Savings goal not found.', 404)); return res.status(204).send(); } catch (error) { return next(error); } });
router.post('/:id/contributions', async (req, res, next) => { try { const goal = await savingsGoalService.addContribution(req.user.id, req.params.id, req.body || {}); if (!goal) return next(new AppError('Savings goal not found.', 404)); return res.status(201).json(goal); } catch (error) { return next(error); } });
router.delete('/contributions/:contributionId', async (req, res, next) => { try { const deleted = await savingsGoalService.removeContribution(req.user.id, req.params.contributionId); if (!deleted) return next(new AppError('Contribution not found.', 404)); return res.status(204).send(); } catch (error) { return next(error); } });
module.exports = router;
